### ISSUE TITLE
Barbershop template / ToDo

### ISSUE THREAD

**Issue by pascalandy** [pascalandy/play-with-ghost#14]
- [x] Integrate a button library to the template
- [x] Many glitch based of Casper 2.0
- [x] other stuff maybe

**Comment by pascalandy** [comment]
Well just see commits in https://github.com/firepress-org/FirePress_Klimax2
